### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by I-Skid** [DamagingRose/Rose-Injector#102]
Please all the folders and files make my brain hurt, simpler the setup is the better the rat is. I can help you customize your readme. make it look better and other things.

bcuz is looks 🤮 rn:
![image](https://github.com/DamagingRose/Rose-Injector/assets/136647828/135fab3d-bfb2-4cb1-8c03-bc4721c86cdb)

**Comment by Gumbobrot** [comment]
message on discord and yeah i wanted to do the file thing with only one bat yee gonna do it soon
