### ISSUE TITLE
still looks shitty as always

### ISSUE THREAD

**Issue by I-Skid** [DamagingRose/Rose-Injector#104]
Sorry just cant lie :/

**Comment by Gumbobrot** [comment]
then make it better my g

**Comment by Beard3dTurtle** [comment]
blud ur name is "I-Skid", and literally there are better ones out there, this one is not heavily worked on and is a small project

**Comment by Beard3dTurtle** [comment]
> Sorry just cant lie :/

nobody gives af

**Comment by Gumbobrot** [comment]
> blud ur name is "I-Skid", and literally there are better ones out there, this one is not heavily worked on and is a small project

i woulnd't say it's a small porject and we worked heavily on it but yea devs are pretty inactive but we tryna work more on it but yuh i still wouldn't say our readme is ass it does it's job

**Comment by I-Skid** [comment]
you didn't even roll out full of my pull req 💀

**Comment by Gumbobrot** [comment]
i explained in my comment on it that i couldn't because restyled said that there are bugs and i fixed em and did it myself
