### ISSUE TITLE
Add more features

### ISSUE THREAD

**Issue by furax124** [DamagingRose/Rose-Injector#105]
Add more features such steam,wallet,Minecraft,epic,battle net, and more to grabber check powershell token grabber of kdot you can see lot of features it's pretty cool if you gonna add it to rose inject

**Comment by Beard3dTurtle** [comment]
Blud powershell grabber is in a different lang lmao

but noted

**Comment by xpierroz** [comment]
i'm on holidays so i can't do it but it might be released soon

**Comment by Gumbobrot** [comment]
> Add more features such steam,wallet,Minecraft,epic,battle net, and more to grabber check powershell token grabber of kdot you can see lot of features it's pretty cool if you gonna add it to rose inject

okay, thanks we gonn do that soon
