### ISSUE TITLE
it wont open 

### ISSUE THREAD

**Issue by ZeroGirlssb** [DamagingRose/Rose-Injector#110]
when i try to open it it closes, what file do i open to make it open?

**Comment by BridgeKeeper1** [comment]
idk I have an error when opening and it shutsdown

**Comment by BridgeKeeper1** [comment]
NiceGUI ready to go on http://localhost:8000                                                                            Process Process-1:                                                                                                      Traceback (most recent call last):                                                                                        File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap       self.run()                                                                                                            File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 108, in run              self._target(*self._args, **self._kwargs)                                                                             File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\nicegui\native_mode.py", line 38, in open_window                                                                                                                     window = webview.create_window(**window_kwargs)                                                                     AttributeError: type object 'webview' has no attribute 'create_window'                                                  ←[31mERROR←[0m:    Traceback (most recent call last):                                                                     File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 686, in lifespan                                                                                                                         await receive()                                                                                                       File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 569, in __aexit__                                                                                                                        await self._router.shutdown()                                                                                         File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\starlette\routing.py", line 664, in shutdown                                                                                                                         await handler()                                                                                                       File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\nicegui\nicegui.py", line 103, in handle_shutdown                                                                                                                    app.native.main_window.signal_server_shutdown()                                                                     AttributeError: 'WindowProxy' object has no attribute 'signal_server_shutdown'                                                                                                                                                                  ←[31mERROR←[0m:    Application shutdown failed. Exiting.

**Comment by Gumbobrot** [comment]
Hi!

So by your information that was included into this issue, I assume that you already downloaded the ZIP file. 

You need to extract it. (You can do that by right clicking the ZIP file and then clicking `Unzip`.)

After you have done that you need to go into the extracted directory.

In there the only thing you need to do is double left click on the `start.bat` file.

Please let me know if that doesn't work. :D

**Comment by Gumbobrot** [comment]
@ZeroGirlssb

**Comment by Gumbobrot** [comment]
Closing this issue now due to inactivity.
