### ISSUE TITLE
better give credits now

### ISSUE THREAD

**Issue by yxvi** [DamagingRose/Rose-Injector#4]
you know whos the main creator LOL

**Comment by Gumbobrot** [comment]
bro we complete overrode everything, and no, are you the creator of wasp? you also just skidded it without giving credits

**Comment by ICExFS** [comment]
who r u

**Comment by Gumbobrot** [comment]
ignore him

**Comment by yxvi** [comment]
sounds good

**Comment by yxvi** [comment]
wheres the main project? this is just a injector

**Comment by suvan1911** [comment]
> wheres the main project? this is just a injector

in the source folder

**Comment by yxvi** [comment]
ah i see thanks

**Comment by yxvi** [comment]
> bro we complete overrode everything, and no, are you the creator of wasp? you also just skidded it without giving credits

no im yuvi
