### ISSUE TITLE
VT-Bypass

### ISSUE THREAD

**Issue by 6nz** [DamagingRose/Rose-Injector#45]
https://github.com/6nz/virustotal-vm-blacklist/blob/main/main.py
https://github.com/6nz/virustotal-vm-blacklist
https://github.com/Lawxsz/bypass-virus-total

**Comment by xpierroz** [comment]
thanks a lot, i'll implement it later

**Comment by 6nz** [comment]
https://github.com/6nz/virustotal-vm-blacklist/blob/main/main.py

**Comment by Gumbobrot** [comment]
could you check the code and see if it's working correctly :) i directly added it to the beginning from main.py @6nz
