### ISSUE TITLE
Project discontinued/paused by head dev

### ISSUE THREAD

**Issue by Gumbobrot** [DamagingRose/Rose-Injector#82]
## First word
Hey, so this is for everyone who wonders why this project is not getting so many updates as it got first/not getting any updates.

## What happened?
So basically, I'm an anti-co-worker. My work is shit and because I don't know how to handle a repo as a team, my developers left me. I thought I needed to discuss everything and I'm just a shit dev.

## How will it be going now?
I won't update it in the next time. I can't tell you when I will start to work on it again. I even need to get to know more about python and batch. I'm currently even going mroe outside, so I would't even have had time. :)

## Contact
If you ran into any other trouble, check out the readme form this project to join our discord or add me on Discord (the discord link on the readme is outdated so wait for me to fix it and put the new invite link or use the invite link i posted here. because of the dispute with the other devs, I created my own new discord server, so dont join the one from the readme. Currently, the old one is still in it.)
https://discord.com/users/1095365517243600947
https://discord.gg/ **creaing-new-one-soon**

**Comment by xpierroz** [comment]
FUCK THIS SHIT WE GOING BACK BABYYYYYYYYYYYY

**Comment by Gumbobrot** [comment]
dont open, but yeah
