### ISSUE TITLE
reporting this to github lmao

### ISSUE THREAD

**Issue by yxvi** [DamagingRose/Rose-Injector#83]
L

**Comment by yxvi** [comment]
idc if you stole or not this is a reverse malware

**Comment by xpierroz** [comment]
what's the reverse malware lmao? you could you précise where's there a reverse malware? because i'm only seeing accusation and no proof lmao

**Comment by Gumbobrot** [comment]
> sorry gentlmen but as a previous owner what the fuck has been stolen without credit? absolutly nothing. the main grabber has been totally remade using different file and shit, i made the ui and i made the rat. could you tell me more about what did we steal lmao?

pierro message me on dc
Gumbobrot#4888

**Comment by Gumbobrot** [comment]
> idc if you stole or not this is a reverse malware

1. you are the only skid here 2. you said a few weeks ago, this was **your** malware and you created it 3. why are you terrorizing us? we can talk bro, what is your fricking problem?

**Comment by xpierroz** [comment]
no, they gonna say that we are discussing private because we're in fault. i don't agree, i worked on this and i know nothing was stolen without credit lol, still waiting for a proof?

**Comment by xpierroz** [comment]
no, they gonna say that we are discussing private because we're in fault. i don't agree, i worked on this and i know nothing was stolen without credit lol, still waiting for a proof?

**Comment by Gumbobrot** [comment]
> no, they gonna say that we are discussing private because we're in fault. i don't agree, i worked on this and i know nothing was stolen without credit lol, still waiting for a proof? 

check out this bro hahahha
https://ibb.co/sVvMNcF
💀

**Comment by yxvi** [comment]
☠️ ☠️ ☠️ ☠️ ☠️ ☠️ ☠️ ☠️ ☠️ ☠️ ☠️ ☠️ ☠️ ☠️ ☠️ ☠️ ☠️ ☠️ ☠️ ☠️ ☠️ ☠️ ☠️ ☠️ ☠️ ☠️ ☠️ ☠️ ☠️ ☠️ ☠️ ☠️ ☠️

**Comment by xpierroz** [comment]
@yxvi im still waiting for you to show me where i stole/put a dual hook/malware lol
