### ISSUE TITLE
got a email from github security

### ISSUE THREAD

**Issue by yxvi** [DamagingRose/Rose-Injector#86]
they said they would look into it 🤣

**Comment by xpierroz** [comment]
as i said in #83 , i'm still waiting for you to show me where in the code is there a malware/dual hook lmfao

**Comment by Gumbobrot** [comment]
> sorry to interject but isn't @yxvi's behaviour considered as spam? i mean, constantly creating new issues without a real reason of reporting a problem (there is literally a [Discussions](https://github.com/DamagingRose/Rose-Injector/discussions) tab to have a convo here), calling you skids and so on. from my understanding, this behaviour should be reported to github, am i wrong?

yes, i really think so. when i got some time i will look into how to report spammers
