### ISSUE TITLE
I have a idea dont know if it working

### ISSUE THREAD

**Issue by TornLotus** [DamagingRose/Rose-Injector#89]
Hey guys i had the idea if it is might possible to do an option where it is possible to atatch .exe files to the injector. Like if i have a other virus, grabber etc. That i can atatch that and then just have one file

**Comment by xpierroz** [comment]
An .exe can't be attached to another .exe to my knowledge, however we can either:
* Put all of the grabber's file into one main.py file and write the content of main.py at the beggining of another Python scrips, but it mights block it with the RAT, so we would need to use thread ...
* Create an .exe that executes 2 .exe?

What do you want?

**Comment by neek8044** [comment]
> An .exe can't be attached to another .exe to my knowledge, however we can either:
> * Put all of the grabber's file into one main.py file and write the content of main.py at the beggining of another Python scrips, but it mights block it with the RAT, so we would need to use thread ...
> * Create an .exe that executes 2 .exe?
> 
> What do you want?

Depending on the way you package/build the main.py you might be able to add the grabber.exe locally with the main.py. For example, pyinstaller has the `--add-data` option and you can call a file as if it was in the local folder, but in reality it will be embedded inside the builded exe itself.

**Comment by neek8044** [comment]
I haven't really gone through the code of the repo to understand it, but my best bet would be to run it when the rose grabber starts, using a parallel subprocess. 

I will try understanding the code of how Rose is being built and if i accomplish to embed the feature somehow I will open a pull request.

**Comment by Gumbobrot** [comment]
Wtf are you dumb

**Comment by Gumbobrot** [comment]
Use a binder to bind multiple exe files to one

**Comment by Gumbobrot** [comment]
@TornLotus
https://github.com/UnamSanctam/UnamBinder
Use this one
I will add an option for it to the grabber tho

**Comment by Gumbobrot** [comment]
@xpierroz @neek8044 stop talking shit about any ass pyinstaller stuff, binder with instant drop way better
