### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by BDevelopment1** [DamagingRose/Rose-Injector#94]
How to Build Exe file.. also when i tried to click the build botton it doesn't include the .exe file

**Comment by neek8044** [comment]
Once you have set all your options and click the build button it will start compiling/building the exe. You will get a notification in the app window once it is done (top right corner) indicating it has finished building. 

In case I misunderstood your problem please provide some additional information, such as the steps you took between the time you opened the app and the time you encountered the issue, or at least a screenshot (or video recording if you'd like), especially the terminal window from where you ran the python script to see if there were any errors.

**Comment by xpierroz** [comment]
thanks for the reply my g

**Comment by neek8044** [comment]
> thanks for the reply my g

np

**Comment by Gumbobrot** [comment]
@neek8044 nahh buddy you gimme your dc rn we gonna talk and i'mgonna add you ig you so good i  fixing this issue shit

**Comment by neek8044** [comment]
Here is my Discord: Neek#8044. I am inactive on Instagram so it won't be use finding me there, though if you do want to find me, I have the same username

**Comment by Gumbobrot** [comment]
bruh you not be accepting reqs change to everyone or add me Gumbobrot#9087

**Comment by xpierroz** [comment]
i'm going to fix all the stuff withing the next 3 days
